name: crontab - Cloud Functions Deploy

on:
  push:
    branches:
      - develop
      - release/internal
      - release/staging
      - release/prod

    paths:
      - 'functions/src/crontab/**'

  workflow_dispatch:
  
env:
  BRANCH-NAME: ${GITHUB_REF##*/}
  CF_NAME: crontab
  CF_ENTRY: cj_notifications
  TRIGGER_EVENT: "trigger-http"
#  TRIGGER_RESOURCE: 'databases/(default)/documents/users/{uid}/bioScans/{testId}'


jobs:
  build-cloud-run:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment values
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/${{env.BRANCH-NAME}}.env

      - name: Setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v0


      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/${{ env.PROJECT_CODE }}/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github"
          service_account: ${{ env.GITHUB_SERVICE_ACCOUNT }}

      - name: Shipping the code
        run: |
            cd functions/src/${{env.CF_NAME}}
            gcloud functions deploy ${{ env.CF_NAME }} --entry-point=${{env.CF_ENTRY }} \
                   --runtime=python39 \
                   --set-env-vars=GCP_PROJECT=${{env.PROJECT_ID}},REGION=${{env.REGION}},PROJECT_NUMBER=${{env.PROJECT_CODE}} \
                   --max-instances=2 \
                   --memory=256MB \
                   --${{env.TRIGGER_EVENT}} \
                   --allow-unauthenticated \
                   --project ${{env.PROJECT_ID}} \
                   --region ${{ env.REGION }} \
                   --service-account ${{ env.GITHUB_SERVICE_ACCOUNT }}