name: Testing cache deploy

on:
  push:
    branches:
      - develop
      - feature/cache

  workflow_dispatch:

jobs:
  build-firebase-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm install
        if: steps.cache-npm.outputs.cache-hit != 'true'

      - name: List the state of node modules
        run: npm run list

      - name: Build
        run: npm run build

      - name: Test
        run: npm test