name: Testing cache deploy

on:
  push:
    branches:
      - develop
      - feature/cache

  workflow_dispatch:

env:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-firebase-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'npm'
          cache-key: 'node-:os:-:channel:-:version:-:arch:-:hash:'
          cache-dependency-path: package-lock.json